### ISSUE TITLE
option.log.child is not a function

### ISSUE THREAD

**Issue by zhaojinpeng111** [QuorumDMS/ftp-srv#300]
hello there,
new FtpSrv by this
```
const ftpServer = new FtpSrv( {
  ...
  log: console
  })
```
what I got
```
xxxxxx\node_modules\ftp-srv\src\connection.js:18
    this.log = options.log.child({id: this.id, ip: this.ip});
                           ^

TypeError: options.log.child is not a function
    at new FtpConnection (xxxxxx\node_modules\ftp-srv\src\connection.js:18:28)
    at Server.serverConnectionHandler (xxxxxx\node_modules\ftp-srv\src\index.js:48:24)
    at Server.emit (node:events:390:28)
    at TCP.onconnection (node:net:1577:8)
```

it seems that I cannot change console instance
https://github.com/trentm/node-bunyan#logchild

**why not make it custom by user self?**

**Comment by DevBash1** [comment]
To disable the logs, you can use this.

```js
const bunyan = require("bunyan");

const logger = bunyan.createLogger({
    name: "null",
    stream: fs.createWriteStream("/dev/null"),
});

const ftpServer = new FtpSrv({
  ...
  log: logger
})

```
