### ISSUE TITLE
ftp-srv works on the command line but fails to work programmatically

### ISSUE THREAD

**Issue by zrougeau** [QuorumDMS/ftp-srv#346]
Hello, 

I've tried running the quick-start code without success:

```
// Quick start, create an active ftp server.
const FtpSrv = require('ftp-srv');

const port=21;
const ftpServer = new FtpSrv({
    url: "ftp://0.0.0.0:" + port,
    anonymous: true
});

ftpServer.on('login', ({ connection, username, password }, resolve, reject) => { 
    if(username === 'anonymous' && password === 'anonymous'){
        return resolve({ root:"C:/Users/" });    
    }
    return reject(new errors.GeneralError('Invalid username or password', 401));
});

ftpServer.listen().then(() => { 
    console.log('Ftp server is starting...')
});
```
The error that I receive is this when I use node basic-ftp client or when I try to access it through the file explorer:

```
{"name":"ftp-srv","hostname":"MSI","pid":15544,"level":40,"msg":"Passive URL not set. Passive connections not available.","time":"2022-12-14T14:22:12.691Z","v":0}
{"name":"ftp-srv","hostname":"MSI","pid":15544,"level":30,"protocol":"ftp","ip":"0.0.0.0","port":"21","msg":"Listening","time":"2022-12-14T14:22:12.707Z","v":0}
Ftp server is starting...
{"name":"ftp-srv","hostname":"MSI","pid":15544,"id":"45799256-d07e-41f2-966d-f4d40f366dc2","ip":"127.0.0.1","directive":"USER","level":50,"err":{"message":"errors is not defined","name":"ReferenceError","stack":"ReferenceError: errors is not defined\n    at FtpServer.<anonymous> (C:\\Users\\Zac\\electron_projects\\device-backup\\src\\backend\\FTP_Server.js:14:23)\n    at FtpServer.emit (node:events:527:28)\n    at C:\\Users\\Zac\\electron_projects\\device-backup\\src\\backend\\node_modules\\ftp-srv\\src\\index.js:105:17\n    at Promise._execute (C:\\Users\\Zac\\electron_projects\\device-backup\\src\\backend\\node_modules\\bluebird\\js\\release\\debuggability.js:384:9)\n    at Promise._resolveFromExecutor (C:\\Users\\Zac\\electron_projects\\device-backup\\src\\backend\\node_modules\\bluebird\\js\\release\\promise.js:518:18)\n    at new Promise (C:\\Users\\Zac\\electron_projects\\device-backup\\src\\backend\\node_modules\\bluebird\\js\\release\\promise.js:103:10)\n    at FtpServer.emitPromise (C:\\Users\\Zac\\electron_projects\\device-backup\\src\\backend\\node_modules\\ftp-srv\\src\\index.js:103:12)\n    at C:\\Users\\Zac\\electron_projects\\device-backup\\src\\backend\\node_modules\\ftp-srv\\src\\connection.js:84:28\n    at tryCatcher (C:\\Users\\Zac\\electron_projects\\device-backup\\src\\backend\\node_modules\\bluebird\\js\\release\\util.js:16:23)\n    at Function.Promise.attempt.Promise.try (C:\\Users\\Zac\\electron_projects\\device-backup\\src\\backend\\node_modules\\bluebird\\js\\release\\method.js:39:29)\n    at FtpConnection.login (C:\\Users\\Zac\\electron_projects\\device-backup\\src\\backend\\node_modules\\ftp-srv\\src\\connection.js:79:23)\n    at FtpConnection.handler (C:\\Users\\Zac\\electron_projects\\device-backup\\src\\backend\\node_modules\\ftp-srv\\src\\commands\\registration\\user.js:12:19)\n    at FtpCommands.handle (C:\\Users\\Zac\\electron_projects\\device-backup\\src\\backend\\node_modules\\ftp-srv\\src\\commands\\index.js:70:28)\n    at C:\\Users\\Zac\\electron_projects\\device-backup\\src\\backend\\node_modules\\ftp-srv\\src\\connection.js:47:67\n    at tryCatcher (C:\\Users\\Zac\\electron_projects\\device-backup\\src\\backend\\node_modules\\bluebird\\js\\release\\util.js:16:23)\n    at Object.gotValue (C:\\Users\\Zac\\electron_projects\\device-backup\\src\\backend\\node_modules\\bluebird\\js\\release\\reduce.js:166:18)"},"msg":"errors is not defined","time":"2022-12-14T14:22:50.474Z","v":0} 
```

Additionally, I also get the following error popup in the file explorer:

Windows cannot access this folder. Make sure you have typed the filename correctly and that you have permission to access the folder.

However, the works through the command line:

`ftp-srv ftp://0.0.0.0:21 --root C:/Users/`

**Comment by seyyednaquib** [comment]
You need to open port 21 in your program and features (windows). and also change the IP address in the code: "ftp://***.***.***.***:" + port,

**Comment by zrougeau** [comment]
> You need to open port 21 in your program and features (windows). and also change the IP address in the code: "ftp://_**.**_._**.**_:" + port,

I figured it out, thanks for your help :)
